version: 2.1
jobs:
  build:
      docker:
        - image: circleci/node:dubnium
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            keys:
              - dependencies-{{ .Environment.CACHE_VERSION}}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
              - $CACHE_VERSION-dependencies-
        - run: yarn global add node-gyp && yarn install
        - save_cache:
            paths:
              - node_modules
            key: dependencies-{{ .Environment.CACHE_VERSION}}-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
            keys:
              - dependencies-{{ .Environment.CACHE_VERSION}}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
              - $CACHE_VERSION-dependencies-
      - run: yarn lint
      - run: yarn format:check
  unit_test:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
            keys:
              - dependencies-{{ .Environment.CACHE_VERSION}}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
              - $CACHE_VERSION-dependencies-
      - run: yarn test:ci

workflow:
   jobs:
     - install
     - lint:
       requires:
         - build
     - unit_test:
       requires:
         - build
     
