version: 2.1
jobs:
    build:
      docker:
      - image: circleci/node:dubnium
      steps:
         - checkout
         - run: echo "hellow world"
         - run: yarn global add node-gyp && yarn install
         - save_cache:
             key: CACHE_VERSION-dependencies-{{ checksum "package.json" }}
